version: "3.8"
services:
    nodeserver1:
        build:
            context: ./app
        ports:
            #- "5000:5000"
            - "3000:3000"
        volumes:
            - ./app/public/projetos/:/usr/src/app/public/projetos/
    nodeserver2:
        build:
            context: ./app
        ports:
            #- "5000:5000"
            - "3001:3000"
        volumes:
            - ./app/public/projetos/:/usr/src/app/public/projetos/
    nodeserver3:
        build:
            context: ./app
        ports:
            #- "5000:5000"
            - "3002:3000"
        volumes:
            - ./app/public/projetos/:/usr/src/app/public/projetos/
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            #- "80:80"
            - "50:80"
networks: 
  default:
      name: patroni_uniddrive-net
      external: true 
